### ISSUE TITLE
triage command line should read environment variables for database connection

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#575] opened 2019-01-24 20:49 UTC
For example 

```
TRIAGE_DB_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@food_db/food'
```

If this variable is define in the environment, it should use it instead of asking for a `database.yaml`

**Comment by thcrock** [comment] 2019-01-24 20:51
Duplicate of #419

**Closed by thcrock** 2019-01-24 20:51 UTC
Labels: performance

**Comment by thcrock** [comment] 2019-01-24 21:07
:cowboy_hat_face:
