### ISSUE TITLE
Support multiple events tables

### ISSUE THREAD

**Issue by hakoenig** [dssg/triage#205] opened 2017-09-11 14:42 UTC
One might want to train and predict on different labels. Supporting multiple events tables in the config would be helpful for that. The information which event table was used should also be easily available in the results schema.

**Comment by thcrock** [comment] 2018-01-19 19:31
Thinking about this feature a little more. @hakoenig This issue is referring to running one experiment that tests two different label definitions, right? Right now we support testing two different label definitions just by running two experiments. 

Doing them in one experiment is certainly possible with some changes throughout the codebase.

**Comment by thcrock** [comment] 2018-12-04 17:48
Duplicate of #445 

I know this one is older but 445's text is more up-to-date with what the relevant code looks like now

**Closed by thcrock** 2018-12-04 17:48 UTC
