### ISSUE TITLE
Merge police branch of collate with sub_query_aggregation into master

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#307] opened 2017-12-13 22:30 UTC
_From @harnav on August 8, 2017 16:57_

Currently there are three branches that claim to do this:
`ka/parallel`
`ka/sub_query`
`ka/parallel_pickle_error`
Running the pipeline using `ka/parallel` results in a pickle error. 
While the changes in `ka/parallel_pickle_error` are made on version 0.2.0 of collate which does not work with the police pipeline code. 

_Copied from original issue: dssg/collate#96_

**Comment by jesteria** [comment] 2017-12-13 22:30
_From @harnav on August 8, 2017 17:12_

Works if you use `Python 3.5` in conjunction with `ka/parallel`

**Comment by thcrock** [comment] 2018-01-20 17:46
Duplicate of #250 - closing

**Closed by thcrock** 2018-01-20 17:46 UTC
