### ISSUE TITLE
The features tables are overwriten

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#199] opened 2017-09-07 23:25 UTC
If you modify some parameter in the features block (e.g. the intervals:adding more intervals) the `features` table for that is overwritten.

This behaviour is not desirable. Related to #198

**Comment by thcrock** [comment] 2018-01-19 18:38
If I understand this correctly, this refers to the fact that the `replace` flag sent to the `architect.FeatureGenerator` is not very granular: it only knows whether or not the features table is there, not whether the structure of this has changed. So if you add an interval, it will either reuse it (if `replace` is False) or blow it away and recompute everything (if `replace` is True). There are many things it can do to be smarter, that could involve computing the feature column names and doing a more granular analysis of the table and make smarter decisions about what it wants to do. Intelligently adding or removing columns from an existing feature table, and/or appending rows, would be a nontrivial piece of work, but is worth tracking because it would be a great performance and usability help.

**Comment by thcrock** [comment] 2018-01-20 03:27
This is a duplicate of #264 which has more details. Closing this.

**Closed by thcrock** 2018-01-20 03:27 UTC
Labels: collate, performance, usability-enhancement
